package com.example.mibancaapp.model

data class Card(
    val id: Int = 0,  // Auto-generated by Room
    val cardholderName: String = "",
    val cardNumber: String = "",
    val expirationDate: String = "",
    val userId: String = ""
)